[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
kotb = "C5iJH6xmzE9228AEBNfSRsb8F1LU7SdCzMAAUk535RZo"

[programs.devnet]
kotb = "C5iJH6xmzE9228AEBNfSRsb8F1LU7SdCzMAAUk535RZo"

[programs.mainnet]
kotb = "ATYRjaUqYm87Z86G5DvteEX4RN2RuYKkMdyq8mhud2dp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypairs/devxvxDjeJFTASGdMhfk4UCdCucmSUrzkoA9g6SMs21.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.test.ts'"
initialize = "yarn ts-node scripts/initialize.ts"
initialize-devnet = "yarn ts-node scripts/initialize.ts devnet"
initialize-mainnet = "yarn ts-node scripts/initialize.ts mainnet"
